import os
import torch
import unittest
import sys

sys.path.append("..")
import hextree
import ocnn.octree as octree


class TestHextree(unittest.TestCase):

    def init_points(self):
        points = torch.Tensor([[0, -1, -1, -1], [0, 0, 0, -1], [8, 0.0625, 0.0625, -1]])
        octree_pts = [
            torch.Tensor([[-1, -1, -1], [0, 0, -1]]),
            torch.Tensor([[0.0625, 0.0625, -1]]),
        ]
        normals = torch.Tensor([[1, 0, 0], [-1, 0, 0], [0, 1, 0]])
        features = torch.Tensor([[1, -1], [2, -2], [3, -3]])
        octree_feat = [torch.Tensor([[1, -1], [2, -2]]), torch.Tensor([[3, -3]])]
        labels = torch.Tensor([[0], [2], [2]])
        return hextree.Points(points, normals, features, labels), [
            octree.Points(octree_pts[i], features=octree_feat[i])
            for i in range(len(octree_pts))
        ]

    def build_hextree(self, device):
        point_cloud, _ = self.init_points()
        point_cloud = point_cloud.to(device)
        htree = hextree.Hextree(depth=5, full_depth=1, device=device)
        htree.build_hextree(point_cloud)
        htree = htree.to("cpu")

        # test node number
        nnum = torch.Tensor([1, 16, 32, 48, 48, 48])
        nnum_nempty = torch.Tensor([1, 2, 3, 3, 3, 3])
        self.assertTrue((htree.nnum == nnum).all())
        self.assertTrue((htree.nnum_nempty == nnum_nempty).all())

        # test the children
        children = [
            torch.Tensor([0]),
            torch.Tensor(
                [0, -1, -1, -1, -1, -1, 1, -1, -1, -1, -1, -1, -1, -1, -1, -1]
            ),
            torch.Tensor(
                [
                    0,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    2,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                ]
            ),
            torch.Tensor(
                [
                    0,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    2,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                ]
            ),
            torch.Tensor(
                [
                    0,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    2,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                ]
            ),
            torch.Tensor(
                [
                    0,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    2,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                ]
            ),
        ]
        for d in range(6):
            self.assertTrue((htree.children[d] == children[d]).all())

        # test the signal
        normals = torch.Tensor([[1.0, 0.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 1.0, 0.0]])
        features = torch.Tensor([[1, -1], [2, -2], [3, -3]])
        self.assertTrue((htree.normals[5] == normals).all())
        self.assertTrue((htree.features[5] == features).all())

    def test_build_hextree(self):
        self.build_hextree("cpu")
        if torch.cuda.is_available():
            self.build_hextree("cuda")

    def merge_hextree(self, device):
        point_cloud1, pcds1 = self.init_points()
        point_cloud1 = point_cloud1.to(device)
        point_cloud2, pcds2 = self.init_points()
        point_cloud2 = point_cloud2.to(device)
        htree1 = hextree.Hextree(depth=5, full_depth=1, device=device)
        htree2 = hextree.Hextree(depth=5, full_depth=1, device=device)
        htree1.build_hextree(point_cloud1)
        htree2.build_hextree(point_cloud2)
        htree = hextree.merge_hextrees([htree1, htree2])
        htree = htree.to("cpu")

        nnum = torch.Tensor([1, 16, 32, 48, 48, 48]) * 2
        nnum_nempty = torch.Tensor([1, 2, 3, 3, 3, 3]) * 2
        self.assertTrue((htree.nnum == nnum).all())
        self.assertTrue((htree.nnum_nempty == nnum_nempty).all())

        children = [
            torch.Tensor([0, 1]),
            torch.Tensor(
                [
                    0,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    2,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    3,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                ]
            ),
            torch.Tensor(
                [
                    0,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    2,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    3,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    4,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    5,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                ]
            ),
            torch.Tensor(
                [
                    0,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    2,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    3,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    4,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    5,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                ]
            ),
            torch.Tensor(
                [
                    0,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    2,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    3,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    4,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    5,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                ]
            ),
            torch.Tensor(
                [
                    0,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    2,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    3,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    4,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    5,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                    -1,
                ]
            ),
        ]
        for d in range(6):
            self.assertTrue((htree.children[d] == children[d].long()).all())

        normals = torch.Tensor(
            [[1.0, 0.0, 0.0], [-1.0, 0.0, 0.0], [0.0, 1.0, 0.0]]
        ).repeat(2, 1)
        features = torch.Tensor([[1, -1], [2, -2], [3, -3]]).repeat(2, 1)
        self.assertTrue((htree.normals[5] == normals).all())
        self.assertTrue((htree.features[5] == features).all())

        otrees = []
        for pcds in [pcds1, pcds2]:
            for pcd in pcds:
                pcd = pcd.to(device)
                otree = octree.Octree(depth=5, full_depth=1, device=device)
                otree.build_octree(pcd)
                otree = otree.to("cpu")
                otrees.append(otree)
        otrees = octree.merge_octrees(otrees)

        # test mapping index
        octree_feat = otrees.features[5]
        hextree_feat = htree.features[5]
        o2h = octree_feat[htree.octree2hextree[5]]
        h20 = hextree_feat[htree.hextree2octree[5]]
        self.assertTrue((o2h == hextree_feat).all())
        self.assertTrue((h20 == octree_feat).all())
        self.assertTrue((otrees.key(5, True) == htree.otrees.key(5, True)).all())

    def test_merge_hextree(self):
        self.merge_hextree("cpu")
        if torch.cuda.is_available():
            self.merge_hextree("cuda")


if __name__ == "__main__":
    os.environ["CUDA_VISIBLE_DEVICES"] = "0"
    unittest.main()
