SOLVER:
  gpu: 0,1,2,3
  run: train
  # logdir: logs_test/log_3Dconv_4Dattention_CPE_RPE_huge_d10
  # logdir: logs_test/log_small
  logdir: logs/hoi-for-vis
  best_val: max:mIoU_part

  ckpt_num: 10
  max_epoch: 50
  test_every_epoch: 1
  log_per_iter: 100

  weight_decay: 5e-3
  type: adamw_attn
  lr: 1e-3
  # lr_min: 1e-6
  lr_type: cos
  # warmup_epoch: 5
  rand_seed: 13
  dist_url: tcp://localhost:10002 # for distributed training


DATA:
  train:
    task: hoi4d_SemSeg

    # hextree building
    depth: 10
    full_depth: 3

    # data augmentations
    distort: True
    angle: (0, 9, 0) # HOI4D
    scale: 0.1
    flip: (0.5, 0.5, 0.0)
    uniform: True
    cutmix: 0.0        # no cutmix
    crop_ratio: 1    # random ratio of random cropping
    max_npt: -1    # max point number of random cropping
    # data loading
    has_label: True
    history: 2
    location: /data/wangx/dataset/HOI4D
    filelist: configs/hoi4d_SemSeg/train_data.txt
    batch_size: 1
    shuffle: True
    num_workers: 2

  test:
    task: hoi4d_SemSeg

    # hextree building
    depth: 10
    full_depth: 3

    # data augmentations
    distort: False  # no data augmentation by default
    angle: (5, 5, 180)
    scale: 0.2
    flip: (0.5, 0.5, 0.0)
    uniform: False
    crop_ratio: 0.8
    max_npt:  -1
    cutmix: 0.0   # no cutmix

    # data loading
    has_label: False
    history: 2
    location: /data/wangx/dataset/HOI4D
    filelist: configs/hoi4d_SemSeg/test_data1.txt
    batch_size: 1
    shuffle: False
    num_workers: 1

MODEL:
  name: hexformer_hoi4d_large
  # name: hexformer_hoi4d
  # name: hexformer_hoi4d
  feature: G
  channel: 4
  nout: 49
  nempty: True
  interp: nearest
  sync_bn: True
  find_unused_parameters: False
  use_compile: False

LOSS:
  mask: -1
  num_class: 49
  weighted: False
