SOLVER:
  gpu: 0,1,2,3
  run: train
  logdir: logs/log_run
  best_val: max:mIoU

  ckpt_num: 200
  max_epoch: 250
  test_every_epoch: 1
  log_per_iter: 10

  weight_decay: 0.05
  type: adamw_attn

  lr: 0.0025
  lr_type: step_warmup
  warmup_epoch: 20
  milestones: (100, 200)
  dist_url: tcp://localhost:10002  # for distributed training

DATA:
  train:
    name: kitti

    # hextree building
    depth: 12
    full_depth: 3

    # data augmentations
    distort: True
    angle: (5, 5, 180)
    scale: 0.2
    flip: (0.5, 0.5, 0.0)
    uniform: True
    cutmix: 0.0        # no cutmix
    crop_ratio: 0.8    # random ratio of random cropping
    max_npt: 100000    # max point number of random cropping
    # data loading
    has_label: True
    location: dataset/kitti
    filelist: dataset/kitti/frame4_full/train_data.txt
    batch_size: 2 # for a single GPU, real batch size = GPU_num * batch_size
    shuffle: True
    num_workers: 2

  test:
    name: kitti

    # hextree building
    depth: 12
    full_depth: 3

    # data augmentations
    distort: False  # no data augmentation by default
    angle: (5, 5, 180)
    scale: 0.2
    flip: (0.5, 0.5, 0.0)
    uniform: False
    crop_ratio: 0.8
    max_npt:  -1
    cutmix: 0.0   # no cutmix

    # data loading
    has_label: True
    location: dataset/kitti
    filelist: dataset/kitti/frame4_full/val_data.txt
    batch_size: 2
    shuffle: False
    num_workers: 2

MODEL:
  name: hexsegformer_toy
  feature: P
  channel: 4
  nout: 20
  nempty: True
  interp: nearest
  depth: 12
  sync_bn: True
  find_unused_parameters: False
  # use_compile: True

LOSS:
  mask: -1
  num_class: 20
