SOLVER:
  gpu: 0,1,2,3
  run: train
  logdir: logs/log_all
  best_val: max:mIoU

  ckpt_num: 200
  max_epoch: 300
  test_every_epoch: 5
  log_per_iter: 10

  weight_decay: 0.05
  type: adamw_attn

  lr: 0.0015
  lr_type: step_warmup
  gamma: 0.2
  warmup_epoch: 5
  milestones: (80, 160, 220, 260)
  dist_url: tcp://localhost:10002  # for distributed training

DATA:
  train:
    name: hoi4d

    # hextree building
    depth: 9
    full_depth: 3

    # data augmentations
    distort: True
    # angle: (5, 5, 180)
    angle: (0, 9, 0) # HOI4D
    scale: 0.2
    flip: (0.5, 0.5, 0.0)
    uniform: True
    cutmix: 0.0        # no cutmix
    crop_ratio: 1    # random ratio of random cropping
    max_npt: 120000    # max point number of random cropping
    # data loading
    has_label: True
    location: dataset/hoi4d
    filelist: dataset/hoi4d/frame8_full/train_data.txt
    # filelist: dataset/hoi4d/frame8/train_data1.txt
    batch_size: 10 # for a single GPU, real batch size = GPU_num * batch_size
    shuffle: True
    num_workers: 2

  test:
    name: hoi4d

    # hextree building
    depth: 9
    full_depth: 3

    # data augmentations
    distort: False  # no data augmentation by default
    angle: (5, 5, 180)
    scale: 0.2
    flip: (0.5, 0.5, 0.0)
    uniform: False
    crop_ratio: 0.8
    max_npt:  -1
    cutmix: 0.0   # no cutmix

    # data loading
    has_label: True
    location: dataset/hoi4d
    # filelist: dataset/hoi4d/frame8/val_data1.txt
    filelist: dataset/hoi4d/frame8_full/val_data.txt
    # filelist: dataset/hoi4d/frame8_test/test_data.txt
    batch_size: 8
    shuffle: False
    num_workers: 2

MODEL:
  name: hexsegformer_toy
  feature: R
  channel: 4
  nout: 49
  nempty: True
  interp: nearest
  depth: 9
  sync_bn: True
  find_unused_parameters: False
  # use_compile: True

LOSS:
  mask: -1
  num_class: 49
