SOLVER:
  gpu: 0,1,2,3
  run: train
  logdir: logs/log_MultiScan_new # NOTE: MultiScan has 26 classes
  best_val: max:mIoU_part

  ckpt_num: 20
  max_epoch: 30
  test_every_epoch: 1
  log_per_iter: 100

  weight_decay: 1e-4
  type: adamw_attn
  lr: 2.5e-3
  lr_min: 1e-6
  lr_type: cos
  # warmup_epoch: 5
  # milestones: (70, 140)
  rand_seed: 13
  dist_url: tcp://localhost:10002 # for distributed training

DATA:
  train:
    name: kitti

    # hextree building
    depth: 12
    full_depth: 3

    # data augmentations
    distort: True
    angle: (0, 0, 180)
    scale: 0.05
    flip: (0.5, 0.5, 0.0)
    uniform: True
    cutmix: 0.0 # no cutmix
    # no crop for kitti
    crop_ratio: 0.8 # random ratio of random cropping
    max_npt: -1 # max point number of random cropping
    # data loading
    has_label: True
    history: 0
    location: /mnt/sdc/wangrh/data/SemanticKITTI
    filelist: config/kitti/train_data.txt
    batch_size: 4 # for a single GPU, real batch size = GPU_num * batch_size
    shuffle: True
    num_workers: 1

  test:
    name: kitti

    # hextree building
    depth: 12
    full_depth: 3

    # data augmentations
    distort: False # no data augmentation by default

    # data loading
    has_label: True
    history: 0
    location: /mnt/sdc/wangrh/data/SemanticKITTI
    filelist: config/kitti/val_data.txt
    batch_size: 1
    shuffle: False
    num_workers: 1

MODEL:
  name: hexsegformer_toy
  feature:
    GF # G -> Position txyz (4 channels);
    # F -> Lidar Density (1 channel)
  channel: 5
  nout: 26
  nempty: True
  interp: nearest
  depth: 12
  sync_bn: True
  find_unused_parameters: False
  # use_compile: True

LOSS:
  mask: 0
  num_class: 26
  weighted: False
